[package]
name = "testcrate"
version = "0.1.0"
authors = ["Aleksandr Orlenko <zxteam@protonmail.com>"]

[features]
default = ["lua53"]
lua54 = []
lua53 = []
lua52 = []
lua51 = []
lua-factorio = []

[build-dependencies.factorio-lua-src]
path = ".."
features = ["ucid"]
